name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Run checks for the API
      - name: Install API dependencies
        working-directory: api
        run: npm ci

      - name: Lint API
        working-directory: api
        run: npm run lint --if-present

      - name: Typecheck API
        working-directory: api
        run: npm run typecheck --if-present

      - name: Test API
        working-directory: api
        run: npm test

      # Run checks for the web (optional)
      - name: Install Web dependencies
        working-directory: web
        run: npm ci

      - name: Lint Web
        working-directory: web
        run: npm run lint --if-present

      - name: Typecheck Web
        working-directory: web
        run: npm run typecheck --if-present

      - name: Build Web
        working-directory: web
        run: npm run build --if-present
